# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_set', models.CharField(max_length=200)),
                ('tag_data', models.CharField(max_length=200)),
            ],
        ),
    ]
